#!/bin/bash
echo "introduce el nombre del fichero"
read f
echo "introduce un nombre para tu web"
read t
sed -i "s/titulo/$t/g" $f.html
echo "introduce un titulo para tu página"
read h1
sed -i "s/default_h1/$h1/g" $f.html
echo "introduce el texto que deseas escribir"
read p
sed -i "s/default_p/$p/g" $f.html


